name: mlnotes
description: Machine Learning Notes
markdown: rdiscount
permalink: /:year/:month/:day/:title.html
url: http://zhuhf.github.io
baseurl: /WEB
author: zhuhf
email: zhuhf@outlook.com
pygments: true
safe: true
paginate: 16
auto: true
keywords: [Machine Learning,机器学习,Algorithm,算法,Math,数学,Distributed,分布式]
github: zhuhf
duoshuo: zhuhf

